### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by havenchyk** [develar/electron-complete-builder#2]
Hi, it would be great if you could provide a roadmap, so possible contributers will see the state of plugin.

Doest it make sense?

**Comment by develar** [comment]
0.5.0 released — publish to GitHub releases implemented.

What's next?

This week:
* Windows code signing in a smart way.
* Investigate and document autoupdate on Windows.

Long-term:
* unstable update channels (document how and support publising).
* fix windows-installer (must be async).

**Comment by develar** [comment]
And, obviously, linux support must be implemented.

**Comment by havenchyk** [comment]
@develar Sometimes it cool to have the issue with checkboxes that is open and show the current state on roadmap. It's why I asked it. Thanks anyway!

**Comment by develar** [comment]
@havenchyk Yes, I thought about it. Ok, will do.

**Comment by develar** [comment]
https://github.com/develar/electron-complete-builder/milestones 

Yes. Only 2 tasks. It is what required for me. I am ready to implement other requested features.

i solve practical problems, it is not a student project or experiment or project for fun :)

**Comment by havenchyk** [comment]
Cool, thanks!
