### ISSUE TITLE
appdmg runs as part of `build --dist` on Linux

### ISSUE THREAD

**Issue by ArekSredzki** [develar/electron-complete-builder#6]
If one runs the dist command on linux, the builder will attempt to package the app using appdmg

**Comment by develar** [comment]
Already fixed, but was not published. 0.5.1 is released now.

**Comment by develar** [comment]
Could you please comment #3 — what do you want — rpm, deb or just zip or maybe anything else?

**Comment by ArekSredzki** [comment]
@develar Thanks, definitely deb, rpm would be nice too.
I could use this today, is it something you have experience with or shall I take a stab at it?
Thanks :)
