### ISSUE TITLE
Multi-architecture build support

### ISSUE THREAD

**Issue by ArekSredzki** [develar/electron-complete-builder#7]
It would be great to be able to build for multiple platforms. I believe that electron-builder supports using wine to enable windows build support on other platforms.

I understand that appdmg is a blocker for the OS X builds, but it would be worth looking into what it would take to enable it to work on other platforms as well.

**Comment by ArekSredzki** [comment]
The dream: build for all platforms at once

**Comment by develar** [comment]
In general, you should use CI server. But multi-platform build is supported currently anyway.

If your app doesn't have native dependencies, you can build:

os x: any ([required brew packages](https://github.com/develar/electron-complete-builder/blob/master/developer-readme.md))
linux: linux and windows ([wine and mono required](https://github.com/electronjs/windows-installer/blob/master/.travis.yml))
windows: only windows (linux will be supported soon).

You need just specify `platform` — `linux`, `darwin` or `win32 `.

It seems, you want to specify `--platform=all`, right?

**Comment by develar** [comment]
`--platform=all` supported in 0.5.3.

**Comment by ArekSredzki** [comment]
Good to know, thank you.
I think that part of the issue here is a lack of documentation. The available commands should be outlined in the README.md so that people can pick the tool as fast as possible.

And thanks for adding the all command!
